bt8: disable ip-tiny (conflicts with ip-full)
ip-full and ip-tiny are mutually exclusive (both provide the ip binary).
Enabling ip-full in the previous commit accidentally left ip-tiny=y too,
causing make package/install to fail with:
  ERROR: unable to select packages:
    ip-full: conflicts: ip-tiny[ip=...]
    ip-tiny: conflicts: ip-full[ip=...]

Signed-off-by: fai <mingfai.ma@gmail.com>